module.exports = {
    DATABASE_IP: process.env.DATABASE_IP,
    DATABASE_TYPE: process.env.DATABASE_TYPE || 'mysql',
    DATABASE: process.env.DATABASE || 'vue-shop',
    DATABASE_USER: process.env.DATABASE_USER || 'root',
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD || '123456',
    POOL_MAX = process.env.POOL_MAX || 5,
    POOL_MIN = process.env.POOL_MIN || 0,
    POOL_ACQUIRE = process.env.POOL_ACQUIRE || 30000,
    POOL_IDLE = process.env. POOL_IDLE || 10000,
    REDIS_IP: process.env.REDIS_IP || "redis",
    REDIS_PORT: process.env.REDIS_PORT || 6379,
    SESSION_SECRET: process.env.SESSION_SECRET || 'yoursecret',
    JWT_SECRET: process.env.JWT_SECRET || 'yoursecret',
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    TWILIO_SERVICE_ID: process.env.TWILIO_SERVICE_ID,
}